version: '3.4'
services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Integration testing using a headless chrome browser
  selenium:
    image: selenium/standalone-chrome:4.1.1-20220121
    shm_size: 2gb
    environment:
      VNC_NO_PASSWORD: 1
    ports:
      # VNC
      - 5900:5900
      # No VNC
      - 7900:7900

  # MailHog is an email testing tool for developers.
  smtp:
      image: mailhog/mailhog
      ports:
        - 8025:8025

  auth:
    image: purtontech/barricade:1.2.0
    env_file:
      - .env
    ports:
      - "9091:9090"
    depends_on:
      db:
        condition: service_healthy


  development:
    build: 
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ..:/workspace:cached
      # Give access to ssh keys on the host (Is there a better way to do this?)
      - ~/.ssh:/home/host-ssh:cached
      # We need this so docker in docker works
      - /var/run/docker.sock:/var/run/docker.sock
      - target:/workspace/target # Set target as a volume for performance. 
      # Uncomment the next line to improve performance when using node.
      - node_modules:/workspace/crates/asset-pipeline/node_modules

    environment:
      DATABASE_URL: postgresql://postgres:testpassword@db:5432/postgres?sslmode=disable

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    working_dir: /workspace
    
    depends_on:
      - db

volumes:
  target:
  node_modules:

# for linux
# extra_hosts:
#   - "host.docker.internal:host-gateway"